project:
  type: website
  output-dir: docs

website:
  title: "Daniel Ruan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    code-fold: true
    code-summary: "Show the code"

editor: visual

execute:
  freeze: auto

